# ========================================
# Docker Compose Configuration
# knowledge-hub
# ========================================
name: knowledge-hub

services:
  # ========================================
  # Development Service
  # ========================================
  app:
    build:
      context: .
      dockerfile: ./Dockerfile  # I know it's not necessary, but let's leave it for learning purposes.
    container_name: knowledge-hub
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
    depends_on:
      db:
        condition: service_healthy
      vectordb:
        condition: service_healthy
    ports:
      - '${PORT:-4000}:4000'
    healthcheck:
      # test: ["CMD-SHELL", "curl -f http://localhost:4000/auth || exit 1"]
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:4000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""] # check new approach 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file: .env
    restart: unless-stopped
    networks:
      - knowledge-network

  # ========================================
  # PostgreSQL Database Service
  # ========================================
  db:
    image: postgres:16-alpine
    container_name: knowledge-hub-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - knowledge-network
    
  vectordb:
    image: qdrant/qdrant:v1.17.1
    container_name: qdrant
    env_file: .env
    ports:
      - '127.0.0.1:6333:6333'  # for dev period
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/6333'"]
      # test: ["CMD-SHELL", "curl -f http://localhost:6333/healthz || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - knowledge-network


  # ========================================
  # Adminer
  # ========================================
  adminer:
    image: adminer
    container_name: adminer-hub
    profiles:
      - debug
      - test
    restart: always
    ports:
      - 8080:8080
    networks:
      - knowledge-network 
    depends_on:
      - db
  
volumes:
  postgres_data:
  qdrant_data:
networks:
  knowledge-network:

